// Auto-generated by update_gallery.py. Do not edit manually.
const GALLERY_DATA = [
  {
    "category": "maternity",
    "src": "assets/gallery/maternity/Maternity.jpg",
    "caption": "Maternity",
    "desc": "Elegant fine-art maternity session serving Ahmedabad and Gandhinagar."
  },
  {
    "category": "maternity",
    "src": "assets/gallery/maternity/_A2A2933.jpg",
    "caption": " A2A2933",
    "desc": "Elegant fine-art maternity session serving Ahmedabad and Gandhinagar."
  },
  {
    "category": "maternity",
    "src": "assets/gallery/maternity/_A2A2955.jpg",
    "caption": " A2A2955",
    "desc": "Elegant fine-art maternity session serving Ahmedabad and Gandhinagar."
  },
  {
    "category": "maternity",
    "src": "assets/gallery/maternity/_A2A4436.jpg",
    "caption": " A2A4436",
    "desc": "Elegant fine-art maternity session serving Ahmedabad and Gandhinagar."
  },
  {
    "category": "maternity",
    "src": "assets/gallery/maternity/_A2A4585.jpg",
    "caption": " A2A4585",
    "desc": "Elegant fine-art maternity session serving Ahmedabad and Gandhinagar."
  },
  {
    "category": "maternity",
    "src": "assets/gallery/maternity/_A2A8630.jpg",
    "caption": " A2A8630",
    "desc": "Elegant fine-art maternity session serving Ahmedabad and Gandhinagar."
  },
  {
    "category": "maternity",
    "src": "assets/gallery/maternity/_RCS0208.jpg",
    "caption": " Rcs0208",
    "desc": "Elegant fine-art maternity session serving Ahmedabad and Gandhinagar."
  },
  {
    "category": "maternity",
    "src": "assets/gallery/maternity/_RCS0310.jpg",
    "caption": " Rcs0310",
    "desc": "Elegant fine-art maternity session serving Ahmedabad and Gandhinagar."
  },
  {
    "category": "maternity",
    "src": "assets/gallery/maternity/_RCS0702.jpg",
    "caption": " Rcs0702",
    "desc": "Elegant fine-art maternity session serving Ahmedabad and Gandhinagar."
  },
  {
    "category": "maternity",
    "src": "assets/gallery/maternity/_RCS0752.jpg",
    "caption": " Rcs0752",
    "desc": "Elegant fine-art maternity session serving Ahmedabad and Gandhinagar."
  },
  {
    "category": "maternity",
    "src": "assets/gallery/maternity/_RCS0782.jpg",
    "caption": " Rcs0782",
    "desc": "Elegant fine-art maternity session serving Ahmedabad and Gandhinagar."
  },
  {
    "category": "maternity",
    "src": "assets/gallery/maternity/_RCS0882_1.jpg",
    "caption": " Rcs0882 1",
    "desc": "Elegant fine-art maternity session serving Ahmedabad and Gandhinagar."
  },
  {
    "category": "maternity",
    "src": "assets/gallery/maternity/_RCS0910.jpg",
    "caption": " Rcs0910",
    "desc": "Elegant fine-art maternity session serving Ahmedabad and Gandhinagar."
  },
  {
    "category": "maternity",
    "src": "assets/gallery/maternity/_RCS0946.jpg",
    "caption": " Rcs0946",
    "desc": "Elegant fine-art maternity session serving Ahmedabad and Gandhinagar."
  },
  {
    "category": "newborn",
    "src": "assets/gallery/newborn/Newborn.jpg",
    "caption": "Newborn",
    "desc": "Safe, gentle, and timeless physiological newborn posing in our boutique studio."
  },
  {
    "category": "newborn",
    "src": "assets/gallery/newborn/_RCS0027.jpg",
    "caption": " Rcs0027",
    "desc": "Safe, gentle, and timeless physiological newborn posing in our boutique studio."
  },
  {
    "category": "newborn",
    "src": "assets/gallery/newborn/_RCS0091.jpg",
    "caption": " Rcs0091",
    "desc": "Safe, gentle, and timeless physiological newborn posing in our boutique studio."
  },
  {
    "category": "newborn",
    "src": "assets/gallery/newborn/_RCS0105.jpg",
    "caption": " Rcs0105",
    "desc": "Safe, gentle, and timeless physiological newborn posing in our boutique studio."
  },
  {
    "category": "newborn",
    "src": "assets/gallery/newborn/_RCS0111.jpg",
    "caption": " Rcs0111",
    "desc": "Safe, gentle, and timeless physiological newborn posing in our boutique studio."
  },
  {
    "category": "newborn",
    "src": "assets/gallery/newborn/_RCS0189.jpg",
    "caption": " Rcs0189",
    "desc": "Safe, gentle, and timeless physiological newborn posing in our boutique studio."
  },
  {
    "category": "newborn",
    "src": "assets/gallery/newborn/_RCS0207.jpg",
    "caption": " Rcs0207",
    "desc": "Safe, gentle, and timeless physiological newborn posing in our boutique studio."
  },
  {
    "category": "newborn",
    "src": "assets/gallery/newborn/master edit.jpg",
    "caption": "Master Edit",
    "desc": "Safe, gentle, and timeless physiological newborn posing in our boutique studio."
  },
  {
    "category": "toddler",
    "src": "assets/gallery/toddler/Toddler.jpg",
    "caption": "Toddler",
    "desc": "Joyful children milestone portraits capturing natural play and expressions."
  },
  {
    "category": "toddler",
    "src": "assets/gallery/toddler/_RCS0037.jpg",
    "caption": " Rcs0037",
    "desc": "Joyful children milestone portraits capturing natural play and expressions."
  },
  {
    "category": "toddler",
    "src": "assets/gallery/toddler/_RCS0062.jpg",
    "caption": " Rcs0062",
    "desc": "Joyful children milestone portraits capturing natural play and expressions."
  },
  {
    "category": "toddler",
    "src": "assets/gallery/toddler/_RCS0072.jpg",
    "caption": " Rcs0072",
    "desc": "Joyful children milestone portraits capturing natural play and expressions."
  },
  {
    "category": "toddler",
    "src": "assets/gallery/toddler/_RCS0126.jpg",
    "caption": " Rcs0126",
    "desc": "Joyful children milestone portraits capturing natural play and expressions."
  },
  {
    "category": "toddler",
    "src": "assets/gallery/toddler/_RCS0158.jpg",
    "caption": " Rcs0158",
    "desc": "Joyful children milestone portraits capturing natural play and expressions."
  },
  {
    "category": "toddler",
    "src": "assets/gallery/toddler/_RCS0195.jpg",
    "caption": " Rcs0195",
    "desc": "Joyful children milestone portraits capturing natural play and expressions."
  },
  {
    "category": "toddler",
    "src": "assets/gallery/toddler/_RCS0238.jpg",
    "caption": " Rcs0238",
    "desc": "Joyful children milestone portraits capturing natural play and expressions."
  },
  {
    "category": "toddler",
    "src": "assets/gallery/toddler/_RCS0318.jpg",
    "caption": " Rcs0318",
    "desc": "Joyful children milestone portraits capturing natural play and expressions."
  },
  {
    "category": "toddler",
    "src": "assets/gallery/toddler/_RCS0620.jpg",
    "caption": " Rcs0620",
    "desc": "Joyful children milestone portraits capturing natural play and expressions."
  },
  {
    "category": "toddler",
    "src": "assets/gallery/toddler/_RCS0663.jpg",
    "caption": " Rcs0663",
    "desc": "Joyful children milestone portraits capturing natural play and expressions."
  },
  {
    "category": "toddler",
    "src": "assets/gallery/toddler/_RCS0670.jpg",
    "caption": " Rcs0670",
    "desc": "Joyful children milestone portraits capturing natural play and expressions."
  },
  {
    "category": "kids",
    "src": "assets/gallery/kids/_RCS0121.jpg",
    "caption": " Rcs0121",
    "desc": "Minimalist premium kid portraits with soft editorial studio lighting."
  },
  {
    "category": "kids",
    "src": "assets/gallery/kids/_RCS0149.jpg",
    "caption": " Rcs0149",
    "desc": "Minimalist premium kid portraits with soft editorial studio lighting."
  },
  {
    "category": "kids",
    "src": "assets/gallery/kids/_RCS0650.jpg",
    "caption": " Rcs0650",
    "desc": "Minimalist premium kid portraits with soft editorial studio lighting."
  },
  {
    "category": "kids",
    "src": "assets/gallery/kids/_RCS0681.jpg",
    "caption": " Rcs0681",
    "desc": "Minimalist premium kid portraits with soft editorial studio lighting."
  },
  {
    "category": "kids",
    "src": "assets/gallery/kids/_RCS0784.jpg",
    "caption": " Rcs0784",
    "desc": "Minimalist premium kid portraits with soft editorial studio lighting."
  },
  {
    "category": "kids",
    "src": "assets/gallery/kids/_RCS1112.jpg",
    "caption": " Rcs1112",
    "desc": "Minimalist premium kid portraits with soft editorial studio lighting."
  },
  {
    "category": "kids",
    "src": "assets/gallery/kids/kids.jpg",
    "caption": "Kids",
    "desc": "Minimalist premium kid portraits with soft editorial studio lighting."
  },
  {
    "category": "family",
    "src": "assets/gallery/family/_A2A9150.jpg",
    "caption": " A2A9150",
    "desc": "Warm, authentic portraits capturing deep emotional bonds and togetherness."
  },
  {
    "category": "family",
    "src": "assets/gallery/family/_RCS0113.jpg",
    "caption": " Rcs0113",
    "desc": "Warm, authentic portraits capturing deep emotional bonds and togetherness."
  },
  {
    "category": "family",
    "src": "assets/gallery/family/_RCS0200.jpg",
    "caption": " Rcs0200",
    "desc": "Warm, authentic portraits capturing deep emotional bonds and togetherness."
  },
  {
    "category": "family",
    "src": "assets/gallery/family/_RCS0234.jpg",
    "caption": " Rcs0234",
    "desc": "Warm, authentic portraits capturing deep emotional bonds and togetherness."
  },
  {
    "category": "family",
    "src": "assets/gallery/family/_RCS0267.jpg",
    "caption": " Rcs0267",
    "desc": "Warm, authentic portraits capturing deep emotional bonds and togetherness."
  },
  {
    "category": "family",
    "src": "assets/gallery/family/_RCS0320.jpg",
    "caption": " Rcs0320",
    "desc": "Warm, authentic portraits capturing deep emotional bonds and togetherness."
  },
  {
    "category": "family",
    "src": "assets/gallery/family/_RCS0433.jpg",
    "caption": " Rcs0433",
    "desc": "Warm, authentic portraits capturing deep emotional bonds and togetherness."
  },
  {
    "category": "family",
    "src": "assets/gallery/family/_RCS0859.jpg",
    "caption": " Rcs0859",
    "desc": "Warm, authentic portraits capturing deep emotional bonds and togetherness."
  },
  {
    "category": "family",
    "src": "assets/gallery/family/_RCS0975.jpg",
    "caption": " Rcs0975",
    "desc": "Warm, authentic portraits capturing deep emotional bonds and togetherness."
  },
  {
    "category": "family",
    "src": "assets/gallery/family/_RCS0993.jpg",
    "caption": " Rcs0993",
    "desc": "Warm, authentic portraits capturing deep emotional bonds and togetherness."
  },
  {
    "category": "family",
    "src": "assets/gallery/family/_RCS1010.jpg",
    "caption": " Rcs1010",
    "desc": "Warm, authentic portraits capturing deep emotional bonds and togetherness."
  },
  {
    "category": "family",
    "src": "assets/gallery/family/_RCS1055.jpg",
    "caption": " Rcs1055",
    "desc": "Warm, authentic portraits capturing deep emotional bonds and togetherness."
  },
  {
    "category": "family",
    "src": "assets/gallery/family/_RCS1167.jpg",
    "caption": " Rcs1167",
    "desc": "Warm, authentic portraits capturing deep emotional bonds and togetherness."
  },
  {
    "category": "family",
    "src": "assets/gallery/family/_RCS1244.jpg",
    "caption": " Rcs1244",
    "desc": "Warm, authentic portraits capturing deep emotional bonds and togetherness."
  },
  {
    "category": "family",
    "src": "assets/gallery/family/_RCS1278.jpg",
    "caption": " Rcs1278",
    "desc": "Warm, authentic portraits capturing deep emotional bonds and togetherness."
  },
  {
    "category": "master-edits",
    "src": "assets/gallery/master-edits/master_edit_1.jpg",
    "caption": "Master Edit 1",
    "desc": "Exclusive pixel-by-pixel signature painterly composite fine-art edit."
  },
  {
    "category": "master-edits",
    "src": "assets/gallery/master-edits/master_edit_130.jpg",
    "caption": "Master Edit 130",
    "desc": "Exclusive pixel-by-pixel signature painterly composite fine-art edit."
  },
  {
    "category": "master-edits",
    "src": "assets/gallery/master-edits/master_edit_14.jpg",
    "caption": "Master Edit 14",
    "desc": "Exclusive pixel-by-pixel signature painterly composite fine-art edit."
  },
  {
    "category": "master-edits",
    "src": "assets/gallery/master-edits/master_edit_145.jpg",
    "caption": "Master Edit 145",
    "desc": "Exclusive pixel-by-pixel signature painterly composite fine-art edit."
  },
  {
    "category": "master-edits",
    "src": "assets/gallery/master-edits/master_edit_24.jpg",
    "caption": "Master Edit 24",
    "desc": "Exclusive pixel-by-pixel signature painterly composite fine-art edit."
  },
  {
    "category": "master-edits",
    "src": "assets/gallery/master-edits/master_edit_29.jpg",
    "caption": "Master Edit 29",
    "desc": "Exclusive pixel-by-pixel signature painterly composite fine-art edit."
  },
  {
    "category": "master-edits",
    "src": "assets/gallery/master-edits/master_edit_32.jpg",
    "caption": "Master Edit 32",
    "desc": "Exclusive pixel-by-pixel signature painterly composite fine-art edit."
  },
  {
    "category": "master-edits",
    "src": "assets/gallery/master-edits/master_edit_37.jpg",
    "caption": "Master Edit 37",
    "desc": "Exclusive pixel-by-pixel signature painterly composite fine-art edit."
  },
  {
    "category": "master-edits",
    "src": "assets/gallery/master-edits/master_edit_38.jpg",
    "caption": "Master Edit 38",
    "desc": "Exclusive pixel-by-pixel signature painterly composite fine-art edit."
  },
  {
    "category": "master-edits",
    "src": "assets/gallery/master-edits/master_edit_4.jpg",
    "caption": "Master Edit 4",
    "desc": "Exclusive pixel-by-pixel signature painterly composite fine-art edit."
  },
  {
    "category": "master-edits",
    "src": "assets/gallery/master-edits/master_edit_41.jpg",
    "caption": "Master Edit 41",
    "desc": "Exclusive pixel-by-pixel signature painterly composite fine-art edit."
  },
  {
    "category": "master-edits",
    "src": "assets/gallery/master-edits/master_edit_42.jpg",
    "caption": "Master Edit 42",
    "desc": "Exclusive pixel-by-pixel signature painterly composite fine-art edit."
  },
  {
    "category": "master-edits",
    "src": "assets/gallery/master-edits/master_edit_43.jpg",
    "caption": "Master Edit 43",
    "desc": "Exclusive pixel-by-pixel signature painterly composite fine-art edit."
  },
  {
    "category": "master-edits",
    "src": "assets/gallery/master-edits/master_edit_5.jpg",
    "caption": "Master Edit 5",
    "desc": "Exclusive pixel-by-pixel signature painterly composite fine-art edit."
  },
  {
    "category": "master-edits",
    "src": "assets/gallery/master-edits/master_edit_53.jpg",
    "caption": "Master Edit 53",
    "desc": "Exclusive pixel-by-pixel signature painterly composite fine-art edit."
  },
  {
    "category": "master-edits",
    "src": "assets/gallery/master-edits/master_edit_6.jpg",
    "caption": "Master Edit 6",
    "desc": "Exclusive pixel-by-pixel signature painterly composite fine-art edit."
  },
  {
    "category": "master-edits",
    "src": "assets/gallery/master-edits/master_edit_63.jpg",
    "caption": "Master Edit 63",
    "desc": "Exclusive pixel-by-pixel signature painterly composite fine-art edit."
  },
  {
    "category": "master-edits",
    "src": "assets/gallery/master-edits/master_edit_7.jpg",
    "caption": "Master Edit 7",
    "desc": "Exclusive pixel-by-pixel signature painterly composite fine-art edit."
  },
  {
    "category": "master-edits",
    "src": "assets/gallery/master-edits/master_edit_8.jpg",
    "caption": "Master Edit 8",
    "desc": "Exclusive pixel-by-pixel signature painterly composite fine-art edit."
  },
  {
    "category": "master-edits",
    "src": "assets/gallery/master-edits/master_edit_89.jpg",
    "caption": "Master Edit 89",
    "desc": "Exclusive pixel-by-pixel signature painterly composite fine-art edit."
  }
];
