import os
import json
import re

GALLERY_DIR = "assets/gallery"
OUTPUT_FILE_JS = "gallery_data.js"

IMAGE_EXTENSIONS = {".jpg", ".jpeg", ".png", ".webp", ".gif"}

CATEGORY_DESCRIPTIONS = {
    "maternity": "Elegant fine-art maternity session serving Ahmedabad and Gandhinagar.",
    "newborn": "Safe, gentle, and timeless physiological newborn posing in our boutique studio.",
    "toddler": "Joyful children milestone portraits capturing natural play and expressions.",
    "kids": "Minimalist premium kid portraits with soft editorial studio lighting.",
    "family": "Warm, authentic portraits capturing deep emotional bonds and togetherness.",
    "master-edits": "Exclusive pixel-by-pixel signature painterly composite fine-art edit."
}

def clean_title(filename):
    # Remove extension
    base = os.path.splitext(filename)[0]
    # Replace separators with spaces
    base = re.sub(r'[-_]', ' ', base)
    # Title Case
    return base.title()

def generate_gallery():
    if not os.path.exists(GALLERY_DIR):
        print(f"Error: Directory {GALLERY_DIR} does not exist!")
        return

    items = []
    
    # Categories list in logical order
    categories = ["maternity", "newborn", "toddler", "kids", "family", "master-edits"]
    
    for category in categories:
        cat_path = os.path.join(GALLERY_DIR, category)
        if not os.path.isdir(cat_path):
            continue
            
        # List sorted files to maintain consistency
        files = sorted(os.listdir(cat_path))
        
        for file in files:
            ext = os.path.splitext(file)[1].lower()
            if ext in IMAGE_EXTENSIONS:
                file_path = f"assets/gallery/{category}/{file}"
                title = clean_title(file)
                desc = CATEGORY_DESCRIPTIONS.get(category, "Beautiful fine-art photography portrait.")
                
                items.append({
                    "category": category,
                    "src": file_path,
                    "caption": title,
                    "desc": desc
                })
                
    # Write as JS global variable to bypass CORS on local file:// protocol
    js_content = f"""// Auto-generated by update_gallery.py. Do not edit manually.
const GALLERY_DATA = {json.dumps(items, indent=2, ensure_ascii=False)};
"""
    with open(OUTPUT_FILE_JS, "w", encoding="utf-8") as f:
        f.write(js_content)
        
    print(f"Successfully generated {OUTPUT_FILE_JS} with {len(items)} images!")

if __name__ == "__main__":
    generate_gallery()
