import os
import json
import re

GALLERY_DIR = "assets/gallery"
OUTPUT_FILE_JS = "gallery_data.js"

IMAGE_EXTENSIONS = {".jpg", ".jpeg", ".png", ".webp", ".gif"}

CATEGORY_DESCRIPTIONS = {
    "maternity": "Elegant fine-art maternity session serving Ahmedabad and Gandhinagar.",
    "newborn": "Safe, gentle, and timeless physiological newborn posing in our boutique studio.",
    "toddler": "Joyful children milestone portraits capturing natural play and expressions.",
    "kids": "Minimalist premium kid portraits with soft editorial studio lighting.",
    "family": "Warm, authentic portraits capturing deep emotional bonds and togetherness.",
    "master-edits": "Exclusive pixel-by-pixel signature painterly composite fine-art edit."
}

def clean_title(filename):
    # Remove extension
    base = os.path.splitext(filename)[0]
    # Replace separators with spaces
    base = re.sub(r'[-_]', ' ', base)
    # Title Case
    return base.title()

def generate_gallery():
    if not os.path.exists(GALLERY_DIR):
        print(f"Error: Directory {GALLERY_DIR} does not exist!")
        return

    # Try to read existing gallery data to preserve order of old images
    existing_items = []
    if os.path.exists(OUTPUT_FILE_JS):
        try:
            with open(OUTPUT_FILE_JS, "r", encoding="utf-8") as f:
                content = f.read()
                match = re.search(r"const GALLERY_DATA = (\[.*?\]);", content, re.DOTALL)
                if match:
                    existing_items = json.loads(match.group(1))
        except Exception as e:
            print(f"Warning: Could not parse existing {OUTPUT_FILE_JS}: {e}")

    items = []
    
    # Categories list in logical order
    categories = ["maternity", "newborn", "toddler", "kids", "family", "master-edits"]
    
    for category in categories:
        cat_path = os.path.join(GALLERY_DIR, category)
        if not os.path.isdir(cat_path):
            continue
            
        # Get all files on disk
        files = sorted(os.listdir(cat_path))
        
        # Filter to image paths
        cat_image_paths = []
        for file in files:
            ext = os.path.splitext(file)[1].lower()
            if ext in IMAGE_EXTENSIONS:
                file_path = f"assets/gallery/{category}/{file}"
                cat_image_paths.append(file_path)
                
        # Get existing items for this category that still exist on disk
        cat_existing = [item for item in existing_items if item.get("category") == category and item.get("src") in cat_image_paths]
        cat_existing_srcs = {item["src"] for item in cat_existing}
        
        # Find new files that are not in the existing array
        cat_new_srcs = [src for src in cat_image_paths if src not in cat_existing_srcs]
        
        # Sort new files by modification time descending (newest first)
        cat_new_srcs.sort(key=lambda src: os.path.getmtime(src), reverse=True)
        
        # Create records for new files
        cat_new_items = []
        for src in cat_new_srcs:
            filename = os.path.basename(src)
            title = clean_title(filename)
            desc = CATEGORY_DESCRIPTIONS.get(category, "Beautiful fine-art photography portrait.")
            cat_new_items.append({
                "category": category,
                "src": src,
                "caption": title,
                "desc": desc
            })
            
        # Combine: new files first, then existing files
        items.extend(cat_new_items + cat_existing)
                
    # Write as JS global variable to bypass CORS on local file:// protocol
    js_content = f"""// Auto-generated by update_gallery.py. Do not edit manually.
const GALLERY_DATA = {json.dumps(items, indent=2, ensure_ascii=False)};
"""
    with open(OUTPUT_FILE_JS, "w", encoding="utf-8") as f:
        f.write(js_content)
        
    print(f"Successfully generated {OUTPUT_FILE_JS} with {len(items)} images!")

if __name__ == "__main__":
    generate_gallery()
